- .gitignore
- MANIFEST.in
- grants_tagger/predict.py
- setup.py
Fixes #8 
Release of version 2020.06.0 of grants tagger. This is the first release from grants tagger and it consists of an improvement for the science tagger projects that combines the previously used Scibert slighly improved and a much improved tfidf-svm together in an ensemble model. It achieves 73%. Human performance is around 80% so the gap is narrowing.
> Release ensemble SciBERT-TFIDF-SVM

- setup.py
Pins version of WellcomeML to the newest to have reproducible builds
> Pin version of WellcomeML

- grants_tagger/predict.py
- grants_tagger/tag_grants.py
https://trello.com/c/thI1pvAF
Tagging sample of grants for quality control by Kirstin. This PR adds the ability to tag with different thresholds, the intention is to tag with thresholds 0.3, 0.5, 0.7, 0.9 and kick off discussion about what is the appropriate default.
> Add threshold to tag grants

- setup.py
> Fix dependency conflicts

- .gitignore
- configs/disease_mesh/2020.07.0.ini
- docs/mesh_results.md
- grants_tagger/create_mesh_label_binarizer.py
- grants_tagger/filter_disease_codes.py
- grants_tagger/preprocess_mesh.py
- grants_tagger/train.py
- scripts/run_mesh_config.sh
- tests/test_preprocess_mesh.py
- tests/test_train.py
This PR adds the necessary code to train the baseline disease model based on Mesh. To do so
- it introduces a config file to run all steps for training the disease mesh model
- adds a config and the ability to parse params from a config in all related files
- adds y_batch_size param to train to split training on multiple labels to make it more memory friendly.
It lacks
* any changes that will be needed to package the model / code, pending discussion with @jdu as to how to package / ship the 75GB model
> Train package disease model

- grants_tagger/filter_disease_codes.py
Very simple update but the python file was currently only generating the descriptor name and tree number, but not the actual MESH code (descriptorUI) so I added this in.
> Added in the descriptorUI to filter_disease_codes.py

- configs/2020.10.0.ini
- configs/2020.10.1.ini
- configs/2020.10.10.ini
- configs/2020.10.11.ini
- configs/2020.10.12.ini
- configs/2020.10.13.ini
- configs/2020.10.14.ini
- configs/2020.10.15.ini
- configs/2020.10.2.ini
- configs/2020.10.3.ini
- configs/2020.10.4.ini
- configs/2020.10.5.ini
- configs/2020.10.6.ini
- configs/2020.10.7.ini
- configs/2020.10.8.ini
- configs/2020.10.9.ini
- docs/results.md
- grants_tagger/preprocess.py
Some of our grants lack a Synopsis but contain a Lay Summary or Research question so this investigation is all about understanding how our model performs in those fields and whether we should apply it to all of them together or individuall or train a new model per field. The summary results below. What is decided is to use the same model and apply it to all available text concatenated which seems to perform the best.
> More text investigation

- grants_tagger/evaluate_model.py
> Convert threshold to float before evaluating

- Makefile
- grants_tagger/__main__.py
- grants_tagger/create_prodigy_data.py
- grants_tagger/evaluate_mesh_on_grants.py
- grants_tagger/evaluate_mti.py
- grants_tagger/evaluate_scispacy_meshtagger.py
- grants_tagger/optimise_params.py
- grants_tagger/predict.py
- grants_tagger/train.py
- requirements_test.txt
- setup.py
- tests/test_create_prodigy_data.py
- tests/test_evaluate_human.py
- tests/test_evaluate_mesh_on_grants.py
- tests/test_evaluate_mti.py
- tests/test_evaluate_scispacy.py
- tests/test_main.py
- tests/test_pretrain.py
- tests/test_train.py
Adds tests and fixes bugs along the way
Fixes #19
> Increase test coverage

- docs/literature_review.md
Adds a summary of the literature review I did. The main points I am adding have to do with things relevant to the project. Happy to add more information in case you think they are useful for others though.
> Add biomedical transformers review

- configs/2020.04.3.ini
- configs/2021.03.0.ini
- configs/2021.03.1.ini
- docs/results.md
- grants_tagger/__main__.py
- grants_tagger/models.py
- grants_tagger/train.py
- requirements.txt
- tests/test_models.py
Add experiments for using Transformers tokenizer for science tagging
> Transformers tokenizer experiment for science tags

- Makefile.streamlit
Adds a new Makefile.streamlit for building and deploying the streamlit container to ECR for deployment to the cluster.
> Makefile.streamlit

- grants_tagger/utils.py
> Remove tensorflow from utils as its not used

- .travis.yml
- README.md
> Fix travis and badges after switch to main

- grants_tagger/models/mesh_tfidf_svm.py
This helps us reduce size in the same that XLinear does and that I described in the blog post. Eventually MeshTfidfSVM might become an in house alternative to XLinear.
Fixes #114
> Save sparse weights in MeshTfidfSVM

- .travis.yml
- Makefile
- scripts/download_bioasq_test_data.py
- scripts/submit_bioasq_test_results.py
- scripts/tag_bioasq_test_data.py
- tox.ini
Add scripts to download, tag and submit data to the BioASQ competition which automates an otherwise manual process.
To release:
* `make build`
> Add download, tag and submit scripts for bioasq

- Makefile
- pipelines/bioasq/dvc.lock
- pipelines/bioasq/dvc.yaml
Run bioasq pipleine for batch 8
> Submit bioasq batch 8

- dvc.lock
- pipelines/bioasq/dvc.lock
- pipelines/bioasq/dvc.yaml
Submit bioasq 9 results
To release:
* `make build`
> Modify bioasq pipeline to submit results

- pipelines/bioasq/dvc.lock
- pipelines/bioasq/dvc.yaml
Run pipeline for batch 11 of BioASQ.
Note that I had to rename `params.json` of mesh-linear to`param.json` to make the pipeline work. Something seems to maybe have broken it at some point.
> Add bioasq batch 11

- Dockerfile.xlinear
- README.md
- configs/mesh/2021.10.1.ini
- configs/mesh/2021.12.0.ini
- configs/mesh/2022.3.1.ini
- configs/mesh/2022.9.0.ini
- configs/mesh/demo-fast.ini
- configs/mesh/demo.ini
- dvc.lock
- dvc.yaml
- grants_tagger/cli.py
- grants_tagger/evaluate_mesh_on_grants.py
- grants_tagger/models/mesh_xlinear.py
- grants_tagger/models/utils.py
- grants_tagger/predict.py
- grants_tagger/preprocess_mesh.py
- grants_tagger/slim/mesh_xlinear.py
- grants_tagger/train.py
- notebooks/2.Xlinear-Training-Example.ipynb
- params.yaml
- requirements.txt
- setup.py
- unpinned_requirements.txt
> Decouple prod code

- grants_tagger/models/bert_mesh.py
- grants_tagger/predict.py
- tests/test_cli.py
- tests/test_evaluate_model.py
- tests/test_predict.py
Fixed predict function to return proper labels. Done so replicating the code [from here](https://huggingface.co/Wellcome/WellcomeBertMesh)
> fix predict function

- requirements.txt
- scripts/create_grants_sample.py
- unpinned_requirements.txt
Add script that does stratified sampling on the grants data based on the `for_first_level_name` column.
> 257 create stratified sample for grants

- grants_tagger/predict.py
- scripts/create_grants_sample.py
- tests/test_predict.py
Add support for batch inference in the predict command.
Add possiblity to pre-annotate your grants data in the script using WellcomeBertMesh.
> add possibility to do batched inference and pre-annotate the grants
