wellcometrust/grants_tagger

grants_tagger/filter_disease_codes.py
Hi Nick, 
I have made some changes in the filter_disease_codes.py which came up when I walked through it with Kirstin. They changes contribute to two items:
- previously only codes starting with a 'C' were included. We have now also included codes starting with 'F03' (mental disorders) and excluded codes starting with 'C22' (animal diseases)
- I have added some code so the resulting codes & names can be exported as a .csv, which makes it easier to check/use the output
=> slightly updated filter_disease_codes.py

grants_tagger/predict_mesh.py, grants_tagger/tag_grants_with_mesh.py, setup.py, tests/test_predict_mesh.py, tests/test_tag_grants_with_mesh.py
This PR exposes a predict function for tagging grants with mesh. It also creates a function to tag grants which is used for quality controls but could be more closely align with the function / task that runs in airflow / argo.
It also updated the version to reflect these changes which will be required when integrating with argo.
In the spirit of increasing test coverage I wrote tests which make a heavy use of temp files due to the nature of the functions i am testing. If there is a better way to write those tests by refactoring some code do say. A bit of the test code is repeated as well which I think is common in tests but again if there is a better way i am keen to hear it.
=> Predict mesh

Makefile, grants_tagger/predict.py, grants_tagger/tag_grants.py, setup.py, tests/test_predict.py, tests/test_tag_grants.py
Adds a new predict function for science tagging that work on multiple grants at the same time which speeds up inference because it allows for matrix multiplications to happen.
At the same time we add a similar to predict_mesh test which makes use of a test model. To do so we had to move away from hard coding the models to pass them as params. As for science tagging those models are packaged into the wheel by default the function can find them unlike mesh that models need to become available via a different route.
=> Add faster predict and tests

Makefile, docs/mesh_results.md, scripts/evaluate_mesh_on_grants.py
This script evaluates the current mesh model performance (tfidf-svm) in our grants data. To do that, Kirstin mapped the ICD codes that the annotators had used to MeSH.
The data collated the model predictions with the gold annotations, in the future we would like to use the model to produce the predictions so that we evaluate different models.
=> Add script that evaluates mesh model on our grants

docs/mesh_results.md, scripts/create_mesh_sample.py, scripts/evaluate_mti.py
Extend script that creates sample to create file in MTI input format.
Add script that reads both files i.e. the sample with the gold tags and the one output that MTI batch service sents back via email and calculates performance for a subset of mesh
=> Calculate performance of MTI

configs/2020.04.2.ini, configs/2020.04.3.ini, grants_tagger/train.py, requirements.txt, tests/test_train.py
Fixes #32. This the problem of not being able to pickle CNNClassifier and BiLSTMClassifier. 
Fixes #34. The above problem was affecting some prior configs in the last stage of saving.
Fixes #33 . A recently introduced feature `y_batch_size` has a bug when not provided
=> Fix save for CNN and BiLSTM in train

configs/2020.10.16.ini, configs/2020.10.17.ini, docs/results.md, grants_tagger/preprocess.py, grants_tagger/train.py, grants_tagger/utils.py, setup.py, tests/test_preprocess.py
This PR goal was to introduce an experiment on running tagging with additional meta columns such as Team and Scheme. This is so that we can evaluate the effects that those variables can have but also to prepare the ground for using additinal fields something also relevant for mesh tagging
To do so I had to
* change preprocessing to include those fields, this was a good opportunity to greatly simplify that module
* represent X as a DataFrame that not only contains list of texts but also those additional fields
* create approaches that combine text with meta features in sklearn
=> Experiments with Team and Scheme for science tagging

grants_tagger/evaluate_model.py, grants_tagger/predict.py, grants_tagger/predict_mesh.py, grants_tagger/tag_grants_with_mesh.py, grants_tagger/train.py, grants_tagger/utils.py, requirements.txt, setup.py, tests/test_evaluate_model.py, tests/test_predict.py, tests/test_predict_mesh.py, tests/test_tag_grants.py, tests/test_tag_grants_with_mesh.py
This PR introduces some changes to evaluate, predict and tag grants in light of the new neural model for disease mesh. There are two main changes here and a couple of smaller ones. The two main changes are
- evaluate ensemble becomes evaluate model and can now evaluate any deployed model
- evaluate model can accept multiple thresholds and in that case it calculates precision and recall for each threshold, a process we follow to set up a static threshold for all tags
There are a couple of things that are not optimal which I plan to fix in the future. Those are
- the model path directs which model is loaded and which predict function is called. it would be ideal if the models behaved in a more similar way after loading and that the path contained some meta information about how to load …
=> Evaluate model

grants_tagger/evaluate_model.py, grants_tagger/predict_mesh.py, grants_tagger/tune_threshold.py, tests/test_predict_mesh.py, tests/test_tune_threshold.py
This PR implements tuning threshold for our tagger inspired from the paper https://doi.org/10.1016/j.patcog.2013.01.012 but modified to be efficient for MeSH. Modifications are:
- Tune threshold on a sample of the test set
- Try a fixed number of thresholds in the continuous range 0 to 1. For example if we want to try 5 thresholds they would be 0 0.2 0.4 0.6 0.8
- Init threshold value instead of starting from an unnecessarily bad init value which requires more iterations
=> Add tune threshold functionality

.travis.yml, Makefile, requirements.txt, setup.py, tests/test_train.py
Updating to WellcomeML contains transition to spacy v3 and
the rewrite of BertClassifier among other things.
~Spacy v3 meant that we needed to update scispacy but as it turns out
this was with its own issues https://github.com/allenai/scispacy/issues/324
so I am postponing that until the issue is resolved and disabling the tests~
BertClassifier switched from referring to pretrained models with short names
to referencing the hugging face names so I am updating the tests here.
=> Update WellcomeML to 2021.2.1

grants_tagger/__main__.py
Transitioning to grants_tagger as a CLI using typer introduced some minor bugs.
This fixes some regarding preprocessing the wellcome science raw data
=> Fix preprocess

grants_tagger/__main__.py, grants_tagger/train.py, grants_tagger/utils.py, requirements.txt, tests/test_train.py, tests/test_utils.py
This PR reintroduces the idea of incremental learning which we first wanted to use to train our Tfidf-SVM baseline.
This time we use our CNN model which leverages `tf.data.Dataset` to implement incremental learning. Note that tensorflow also allows for a generator to be passed in but in that case functionally such as batching, shuffling etc would need to be implemented whereas now it comes for free.
Note that `KerasVectorizer` and `MultiLabelBinarizer` allow for a generator to be passed in so training them efficiently is relatively easy. One thing we need to work around, as is often in this project, is sparse labels. In particular the dataset converts to dense as it returns data but this means that test_data need to be converted back to sparse to fit into memory.
=> Incremental training

.travis.yml, Makefile, grants_tagger/__main__.py, grants_tagger/evaluate_mesh_on_grants.py, grants_tagger/evaluate_model.py, grants_tagger/models.py, grants_tagger/predict.py, grants_tagger/tag_grants.py, grants_tagger/train.py, grants_tagger/tune_threshold.py, grants_tagger/utils.py, requirements.txt, setup.py, tests/test_evaluate_mesh_on_grants.py, tests/test_evaluate_model.py, tests/test_main.py, tests/test_models.py, tests/test_predict.py, tests/test_tag_grants.py, tests/test_train.py, tests/test_utils.py
The main motivation for this PR was that pieces of the implementation that made production models happen was living in different scripts such as train, predict and evaluate. Those were custom adjustments that are not general enough to go to WellcomeML so they ended up in a semi organised way in the project. As progressively these adjustments are quite specific to the some models and in particular those that went to production, the logical thing to do was to introduce custom classes for the production models that hide away the complexity and expose a clean sklearn API such as WellcomeML. In order for this to happen a lot of code needed to move around and some needed to be rewritten hence the big size which as you can see does not introduce a lot of new lines but does move around a lot. …
=> Add classes for production models

.gitignore, Makefile, README.md, data/raw/allMeSH_2021.json.dvc
As I was not able to find a way to use `dvc --glob` to selectively pull and push, I am adding a way for the user to control which data to sync as a separate make command. This way the user can choose to sync the mesh project or not.
`dvc pull` pulls all the data but since `dvc` is meant for production, that is not necessarily bad. A user can safely experiment with the make commands.
=> Split data sync to science and mesh

.gitignore, README.md, grants_tagger/__main__.py, grants_tagger/download_epmc.py, tests/test_download_epmc.py
This PR adds a `download` command to grants tagger so that the Mesh data can be downloaded from EPMC. The rationale is that BioASQ provides the data behind a registration whereas with EPMC it is freely available for all to download without the need to register.
I have copied and reimplemented the EPMC client as because of the volume of the data I needed it to write on the fly so that is more efficient and also handle partial downloads. If these are features we want in WellcomeML we can work towards bringing the two together in the future.
Fixes #54
=> Add download EPMC script

Makefile, README.md, grants_tagger/__main__.py, grants_tagger/download_model.py, unpinned_requirements.txt
Adds functionality to download publicly available models at the moment only `disease_mesh`. At the same time uploads those models when we do a new release.
Fixes #75
=> Download model command

setup.py
The intention of this PR was to make grants_tagger light as discussed
in #99 but this is not as easy as it sounds as `1.4GB` are simply the
size from solely `wellcomeml[tensorflow]==1.2.0` which is a core
dependency of this project.
As part of this PR I am removing uneeded packages (nltk) and those that
depend on our infrastructure which the user will not have access to like
dvc or sagemaker. At a later point we could provide indstruction as to how
to transition dvc and sagemaker functionality to their provided if needed. 
The package ends up taking `1.6GB`, `1.4GB` of which are, as mentioned from
`wellcomeml[tensorflow]==1.2.0`. Reducing futher will need to look into either
removing tensorflow or using a lite version of it.
Fixes #99
[Notion …
=> Ligher grants_tagger

.github/workflows/flake8.yml
Adds Github action to run flake8 which fails if there are errors. The errors can be seen from the logs or by
running `flake8` locally
=> Add flake8 github action

README.md, grants_tagger/__main__.py, grants_tagger/label_binarizer.py, grants_tagger/train.py
Move the create_label_binarizer() in it's own file. Add it to the preprocess step as there was no way of using it through the CLI before.
- [ x ] Updated README
To release:
* `make build`
=> Add label binarizer creation to the preprocess step

README.md, dvc.lock, grants_tagger/__main__.py, grants_tagger/preprocess_mesh.py, grants_tagger/train.py, results/mesh_xlinear_train_info.json, results/scibert_train_info.json, results/science_ensemble.json, results/tfidf_svm.json, results/tfidf_svm_train_info.json, tests/test_preprocess_mesh.py
Both #173 and #160 require a subset of the data to train. The best possible way to provide that subset is to filter by years which is standard practice in this problem. At the moment this is implemented in both PR mentioned but this aims to resolve it for both.
Fixes #109
=> Add year, journal in preprocess mesh

Makefile, README.md, grants_tagger/models/bert_mesh.py, grants_tagger/models/create_model.py, pipelines/bioasq/dvc.lock, pipelines/bioasq/dvc.yaml, scripts/download_bioasq_test_data.py, scripts/submit_bioasq_test_results.py, scripts/tag_bioasq_test_data.py, tests/test_predict.py
Adds BertMesh in models by copying and not refactoring the experimental code in BertMesh. The reason being that at this point we want to maintain moving fast in experimentation while separating what we maintain for "production". As such we do not add code to train BertMesh as this happens still in experimentation mode. Once this becomes more stable we can do that.
DVC sort of up to date.
=> Add BertMesh to models so that we can tag in BioASQ

.pre-commit-config.yaml, dvc.lock, dvc.yaml, grants_tagger/preprocess_mesh.py
Adds a process to generate toy MeSH data, alongside real data, so we can iterate our code faster. 
It disables/comments the dvc pre-commit hook because I will make a lot of changes to it, so no point in re-running every time.
To release:
* `make build`
=> Create pre-process for to toy data

data/processed/WT_mesh_tags_used/tags_used.txt.dvc
Just a dvc hash file which has the location of a text file with all mesh terms that are used by WT
=> dvc hash of mesh terms used by WT
